### ISSUE TITLE
questions on unbeets docker config

### ISSUE THREAD

**Issue by kropewnicki** [smdion/docker-containers#9]
I noticed that there is a 4th field on my docker config 
/etc/localtime 
which is preset to /etc/localtime

You might want to update your documentation on what that should be.

Also, what version of unraid did you target this?

**Comment by smdion** [comment]
The template install for Beets maps it to /etc/localtime on unRAID so it
has the same time and requires no user configuration.

https://github.com/smdion/docker-containers/blob/templates/smdion-repo/Beets.xml

--
Sean Dion

**Comment by kropewnicki** [comment]
I figured it out, I needed to enable the Advanced items on docker config, and then I was able to add Beets.

I will close this issue, but you might want to update your documentation.
